[phases.setup]
nixPkgs = ["bun"]
aptPkgs = ["libssl3", "ca-certificates"]

[phases.install]
cmds = ["cd backend && bun install"]

[phases.build]
cmds = ["cd backend && bun run postinstall"]

[start]
cmd = "cd backend && bun run src/index.ts"
